Qwant/kartotherian_docker

README.md, docker-compose.yml, kartotherian/Dockerfile, kartotherian/cassandra.wait, load_db/Dockerfile, load_db/import_data.sh, load_db/readme.md, tilerator/Dockerfile, tilerator/gen_tiles.sh, tilerator/runserver.sh, tileview/Dockerfile, tileview/LICENSE.md, tileview/index.html, tileview/osm-liberty.json, tileview/readme.md
thus we can display the vector tiles map at `http://localhost:8585`.
The container startup has been refactored a bit too, now tilerator is always runned but wait for the data import process to finish
=> add a tileview container to display a map

README.md
detail how the configuration files for the vector tiles were generated
=> more doc on configuration files

tileview/LICENSE.md, tileview/compare.html, tileview/index.html, tileview/klokan.json, tileview/qwant_style.json, tileview/readme.md, tileview/tileschema.json
=> tileview : mix klokantech and osm liberty styles

tileview/index.html, tileview/qwant_style.json
* clean minzoom uses
* add landuse for cemetery, hospital, schools
* fix tram and subway stops selection
=> Improve style

tileview/index.html
This does not include changes on the geocoder. Photon is still used here.
=> Apply latest updates to tileview

README.md, kartotherian/variables.yaml, load_db/Dockerfile, load_db/import_data.sh, tilerator/Dockerfile, tilerator/gen_tiles.sh, tilerator/variables.yaml, tileview/qwant_style.json
linked to https://github.com/QwantResearch/openmaptiles/pull/1
tested, it works :man_dancing:
=> update after openmaptile new release

load_db/Dockerfile, load_db/import_data.sh
linked to https://github.com/QwantResearch/kartotherian_config/pull/17
=> add external dependencies

load_db/Dockerfile
this way we can do:
docker run <image> pipenv run invoke
=> change the default directory

tileview/Dockerfile
add the icon generation for the debug page
=> add icons to the builder

load_db/Dockerfile
* From **imposm3 0.4.0dev** (2017-05-19) to **imposm 0.6-alpha4** (2018-04-17)
=> Upgrade to imposm 0.6

kartotherian/Dockerfile, tilerator/Dockerfile
Pin specific commits in `tilerator` and `kartotherian` Dockerfile.
=> Pin kartotherian and tilerator versions

docker-compose.yml, load_db/Dockerfile, load_db/import_data.sh, tilerator/Dockerfile, tilerator/config.yaml, tilerator/runserver.sh
remove the redis dependency (we don't need it anymore since https://github.com/QwantResearch/tilerator/pull/5)
change the tilerator configuration to the new format
=> Update to the new tilerator version

kartotherian/Dockerfile, load_db/Dockerfile, tilerator/Dockerfile
linked to https://github.com/QwantResearch/kartotherian_config/pull/34
=> update to openmaptiles 3.8

kartotherian/Dockerfile, load_db/Dockerfile, tilerator/Dockerfile
Following https://github.com/QwantResearch/kartotherian_config/pull/38
=> Update config: Add imposm -quiet option

kartotherian/Dockerfile, load_db/Dockerfile, tilerator/Dockerfile
integrate https://github.com/QwantResearch/kartotherian_config/pull/39
=> update to get a better osm file download

kartotherian/Dockerfile, load_db/Dockerfile, tilerator/Dockerfile
Just update the checkout shawan after the commit removing swimming pools from the karto config: https://github.com/QwantResearch/kartotherian_config/commit/49ed34abc4ed1241f14fb0c7edf5dfe86cd0821c
=> New shawan

kartotherian/Dockerfile, kartotherian/config.yaml
Following https://github.com/QwantResearch/kartotherian/pull/5 and https://github.com/QwantResearch/kartotherian_server/pull/3
=> Make kartotherian more robust to Cassandra errors

load_db/Dockerfile
Simple update the docker after the config QwantResearch/kartotherian_config@b58ff10a41ad9b0e179e2753e0a52d296897f439
=> Clean load db

kartotherian/Dockerfile, kartotherian/config.yaml, kartotherian/variables.yaml, load_db/Dockerfile, tilerator/Dockerfile, tilerator/config.api.yaml, tilerator/config.worker.yaml, tilerator/runserver.sh, tilerator/variables.yaml
* Upgrade from node 6 to node 8
* Update kartotherian_config (following https://github.com/QwantResearch/kartotherian_config/pull/46)
* Update kartotherian / tilerator (following https://github.com/QwantResearch/kartotherian/pull/7 and https://github.com/QwantResearch/tilerator/pull/6)
=> Use node 8 base images, update config

kartotherian/Dockerfile, load_db/Dockerfile, tilerator/Dockerfile
Includes https://github.com/QwantResearch/kartotherian_config/pull/47 
Should fix #68
=> Update kartotherian_config, including new water polygons URL

README.md, kartotherian/Dockerfile, load_db/Dockerfile, tilerator/Dockerfile
Linked to QwantResearch/openmaptiles#19
=> Parks and gardens

load_db/Dockerfile
* Update openmaptiles, to include https://github.com/QwantResearch/openmaptiles/pull/23
* Upgrade to imposm 0.8.1, using a custom release to apply fix from https://github.com/omniscale/imposm3/pull/206
=> Upgrade to imposm 0.8.1

README.md
Broken in 7c3cbcf1d886aef04633526c0ef03513fdc99ce2
=> Fix dead links on README.md

import_data/import-wikidata/wikidata_functions.sql
Avoid searching for view counts when a POI has no Wikidata ID.
On my dev workflow it makes `poi_display_weight` and `layer_poi` calls twice as fast
=> import-wikidata: avoid database lookups when POI has no wikidata ID

kartotherian/Dockerfile, tilerator/Dockerfile, tilerator/config.worker.yaml
Following https://github.com/QwantResearch/kartotherian/pull/9
=> Update kartotherian and tilerator to Node 10

docker-compose.yml, import_data/tasks/tasks.py, load_db/Dockerfile
* Update openmaptiles (following https://github.com/QwantResearch/openmaptiles/pull/28)
* Override `osml10n_kanji_transcript` (defined in osml10n extension) that produces invalid utf8 in database
* Update dependencies
* openmaptiles/postgis image
* imposm 0.10.0
=> Optimization in POIs functions for external import

kartotherian/Dockerfile, tilerator/Dockerfile
Following https://github.com/QwantResearch/kartotherian/pull/10
=> Update qwantresearch/kartotherian to fix tilerator memory usage

docker-compose.yml
To apply fixes described in https://github.com/openmaptiles/openmaptiles-tools/pull/166
=> Update openmaptiles/postgis to use PostGIS 2.4.8

.gitmodules, README.md, import_data/import-wikidata/wikidata_functions.sql, import_data/invoke.yaml, import_data/tasks/tasks.py, kartotherian/Dockerfile, kartotherian/README.md, tilerator/Dockerfile, tilerator/README.md, tileview/Dockerfile, tileview/tileview_conf.json
* Update URLs in configuration, Dockerfile and documentation
* Update submodule remote URL
=> Move from QwantResearch to Qwant organization

import_data/Pipfile.lock, import_data/invoke.yaml, kartotherian/Dockerfile, load_db/Dockerfile, tilerator/Dockerfile
Related PRs to be merged first:
* https://github.com/Qwant/kartotherian/pull/12
* https://github.com/Qwant/openmaptiles/pull/42
In addition to "openmaptiles" and "kartotherian", this PR also upgrade Python dependencies defined in "/import_data" (closes #126).
=> Upgrade dependencies, including Kartotherian and Tilerator to Node 14

import_data/tasks/tasks.py
This check is necessary to prevent potential corruption in the OSM cache maintained by imposm.
See comment in script for more details.
Note that this check could potentially be removed after upgrading to OpenMapTiles 3.12 where materialized views (that require an exclusive lock on refresh) are no longer used.
=> update: Check tiles generation is not in progress before writing to pg

import_data/invoke.yaml
Update wikidata datsets with end of 2022 data
=> Update wikidata datsets
