docker-compose.yml
load_db/import_data.sh

this way we can import twice the data (or import, stop the docker, then
reimport)
The tile generation does not work well when the docker are stopped though :disappointed:

make import_data idempotent

---

load_db/generated_sql.sql

the osm tags were sliced to keep only the names, but we might want to
kepp all OSM tags to be more robust to changes
we need to see the impact on the postgres db size of this change

change the sql to keep all osm tags

---

tileview/Dockerfile

Node v8 is now required to run the builder.

tileview: Use node 8 to build map style

---

load_db/Dockerfile

mapnik german is not required because it has been installed as part of
the osm10n extension

mapnik german is not required

---

kartotherian/Dockerfile
kartotherian/cassandra.wait
tilerator/Dockerfile
tilerator/runserver.sh

Simple verification to check if Cassandra port is open using netcat instead of nmap.

Use netcat instead of nmap for cassandra.wait verification

---

README.md
kartotherian/Dockerfile
load_db/Dockerfile
local-compose.yml
tilerator/Dockerfile
tilerator/config.yaml

note: tilerator now use the default port, so the docker-compose url ofr
it is onlye `http://tilerator`
needs https://github.com/QwantResearch/kartotherian_config/pull/30 (and thus after the config PR merge, we need to update the kartotherian_config sha1 used)

generate tiles as part of the load_db script

---

docker-compose.yml
tilerator/Dockerfile
tilerator/config.api.yaml
tilerator/config.worker.yaml
tilerator/runserver.sh

* `tilerator` will run the API with `uiOnly: true` and will receive jobs requests from load_db service. Default config in kartotherian_config remain unchanged, the API is still accessible via "http://tilerator"
* `tilerator-worker` will launch workers and process tiles, and do not depend on any volume

Split tilerator into two services

---

kartotherian/Dockerfile
load_db/Dockerfile
tilerator/Dockerfile

Use sha256 in Dockerfile base images for `kartotherian`, `tilerator`, and `load_db`.

Pin Dockerfile base images

---

docker-compose.yml
kartotherian/config.yaml
local-compose.yml
telegraf/Dockerfile
telegraf/readme.md
telegraf/telegraf.conf

This PR is not to merge as is, it's a POC to show how to get prometheus metrics from kartotherian.
it uses telegraf to work as a statsd intance and expose prometheus metrics from it.
for the grafana dashboards, we can do something like [wikimedia is doing](https://grafana.wikimedia.org/dashboard/db/service-kartotherian?refresh=5m&orgId=1).
the metrics are (in debug):
* some metrics about the heap
* duration to get tiles, ventilated by layer and zoom level :heart_eyes: 
we now need to check with our CI that this system is ok for them

expose prometheus metrics from kartotherian

---

kartotherian/Dockerfile
kartotherian/config.yaml
tilerator/config.api.yaml
tilerator/config.worker.yaml

* Kartotherian: set `catchMetricsErrors` to prevent worker restart on statsd errors
Following https://github.com/QwantResearch/kartotherian/pull/6
* Tilerator:  
* Read heartbeat timeout from environment
* Default to 30s on tilerator-worker. A worker could be slow to initialize in some cases (eg when all workers are starting simultaneously and all connections to source databases need to be reset)

Update configuration for resilience

---

.travis.yml
telegraf/Dockerfile

4 images will be built automatically on master branch:
* `qwantresearch/kartotherian_load_db`
* `qwantresearch/kartotherian_tilerator`
* `qwantresearch/kartotherian_kartotherian`
* `qwantresearch/kartotherian_telegraf`

Add travis configuration for docker images automatic builds

---

.travis.yml

This change comes in mostly because of #76 (even though it could have come in any other time). It adds check for all branches and prevent push if not on master branch and remove docker log in if not on master branch as well.

Build PRs but don't push if not master

---

import_data/osm_update.sh
import_data/tasks.py

* Remove pre-existing import database (eg, from a previous job that failed)
* Fail on first imposm error in osm_update (errors from piped command used to be ignored)

Improve robustness of import and update jobs

---

kartotherian/Dockerfile
kartotherian/config.yaml
tilerator/Dockerfile
tilerator/config.api.yaml
tilerator/config.worker.yaml
tilerator/gen_tiles.sh
tilerator/runserver.sh

Following https://github.com/QwantResearch/kartotherian/pull/8
* Update Dockerfile for `kartotherian` and `tilerator`
* Update paths to subpackages
* Remove unnecessary symlinks for config files

Use kartotherian monorepo to build tilerator and kartotherian images

---

import_data/osm_update.sh
import_data/tasks.py
import_data/utils/lock.py

* Remove lock file mechanism from `osm_update.sh` script. 
* It is replaced by a lock created by both `load_all` and `run_osm_update` tasks, and uses [`fnctl.flock`](https://docs.python.org/3/library/fcntl.html?highlight=flock#fcntl.flock) to acquire a lock on a file descriptor.

Use a unique lock mechanism for import and updates

---

kartotherian/config.yaml

For compatibility with metrics published by telegraf.
It seems that the new version of service-runner (used by kartotherian) defines "root" as the default prefix.

Define metrics prefix for kartotherian

---

import_data/invoke.yaml
import_data/osm_update.sh
import_data/tasks.py
load_db/Dockerfile

Another step to make osm updates more robust.
In some cases, osmosis fails to parse OSM change files because of a bug in its parsing library.
See https://github.com/openstreetmap/osmosis/pull/50 for more details.
Osmosis is no longer maintained. So it seems more reasonable to switch to [`osmupdate`](https://wiki.openstreetmap.org/wiki/Osmupdate), provided by `osmctools` package.
This change also makes the implementation simpler: no more `JAVACMD_OPTIONS` to override, no more `configuration.txt` file to maintain. And it's no longer required to keep a `sequenceNumber` in the state file.
Osmupdate will simply fetch all changes from OSM servers, based on the **`timestamp`** that is present in `state.txt`. This file (already used by osmosis) keeps track of the latest change file that is …

Replace 'osmosis' with 'osmupdate' to fetch change files

---

exec.py

Manually managing the buffer can lead to overflows, especially when dealing with parallelized code. It seems that that Popen's default behavior is to redirect outputs in streaming, thus this piece of code can be removed without any loss.
The bug can be reproduced by calling the following kind of task, this will be likely to raise an uncatched BlockingIOError at [this line](https://github.com/QwantResearch/kartotherian_docker/blob/20a172edd1359748447815b4e26262f3e708f065/exec.py#L35).
```python
cc_exec = concurrent.futures.ThreadPoolExecutor()
@task
def testing(ctx):
concurrent.futures.wait([
cc_exec.submit(test_print, ctx, '1', 10**4),
cc_exec.submit(test_print, ctx, '2', 10**4),
cc_exec.submit(test_print, ctx, '3', 10**4),
cc_exec.submit(test_print, ctx, '4', 10**4),
])
def …
```

exec.py: no redirect of stdout

---

import_data/invoke.yaml
import_data/tasks/format_stdout.py
import_data/tasks/tasks.py

Speed up import by parallelizing some unrelated tasks.
Results of consecutive runs for imports of Luxembourg on my laptop:
|      branch     | with stats | duration (mm:ss) |
|:---------------:|:----------:|:----------------:|
|      master     |     no     |       14:21      |
| parallel-import |     no     |       10:32      |
|      master     |     yes    |       53:50      |
| parallel-import |     yes    |       37:30      |
| parallel-import + patched openmaptiles |     no    |       6:06      |
Note that the import of borders could internally be parallelized through a PR to openmaptiles: https://gist.github.com/remi-dupre/a963359722ecb7360885cbc390386be7.

parallelize import

---

import_data/invoke.yaml
import_data/tasks/tasks.py
load_db/Dockerfile

* Enable wikidata stats import by default
* Upgrade to imposm v0.9 (with db optimizations: https://github.com/omniscale/imposm3/commit/3b6e6b38f4529ac468580040dff25a0b47a037c9)
* Add logging messages

Enable wikidata stats import by default and optimizations

---

import_data/invoke.yaml
import_data/tasks/format_stdout.py
import_data/tasks/tasks.py

For unclear reasons, applying updates on a geographical pbf extract lead to higher memory requirements for imposm. Possibly because of broken references in the file.
As this feature is only useful for planet files (that are typically downloaded with a several days delay), this PR suggests to apply this pre-import update on these files only.

Disable pbf update on non-planet files (avoid high memory usage by imposm)

---

import_data/Pipfile
import_data/Pipfile.lock
import_data/import-wikidata/wikidata_functions.sql
import_data/tasks/tasks.py

Ensures that weights will correctly be spread from 0.5 to 1 for POIs with a linked Wikipedia page. Also, this makes `poi_display_weight` less dependent of the period of time considered for metrics.
- top 0.1% POIs will have a weight of 1 (in île-de-France only it includes Tour Eiffel, Musé du Louvre, Cathédrale Notre-Dame and Château de Versailles)
- the POIs with the least 10% of page views will have a weight computed by ignoring the Wikipedia page (~ less than 10 views / month on current dataset)
Note that the two percentiles are quite expensive to compute, but will only be computed for the first run of `poi_display_weight`.

display_poi_weight: compute max and min views with percentiles

---

exec.py

Allow to work with several docker_compose prefixes, this allows to keep data for several karthoterian_docker setups. For example:
```bash
./exec.py --namespace karthoterian_lu load-db
docker-compose -p karthoterian_lu -f local-compose.yml -f docker-compose.yml stop
./exec.py --namespace karthoterian_fr load-db-france
docker-compose -p karthoterian_fr -f local-compose.yml -f docker-compose.yml stop
```

add --namespace parameter

---

import_data/invoke.yaml
import_data/osm_update.sh
import_data/tasks/tasks.py

Timeout during POI tiles generation have been observed after several weeks of successive updates.   
A regular REINDEX on `osm_poi_polygon` geometries (which are potentially updated after each run of osm_update to find a centroid for each new polygons) should solve this issue.

Reindex osm_poi_polygon geometries to avoid bloat after successive updates

---

docker-compose.yml
local-compose.yml

Cassandra sets the heap size to 1/4 ram in most situations:
https://docs.datastax.com/en/cassandra-oss/3.x/cassandra/operations/opsTuneJVM.html#Determiningtheheapsize
For testing purposes where all services run on the same machine this value is too high for no benefit.
This PR sets lower values in `local-compose.yml` used on local environments.

Reduce Cassandra memory usage for local runs

---

import_data/invoke.yaml
import_data/tasks/osm_update.py
import_data/tasks/tasks.py
load_db/Dockerfile
load_db/config_base.json
load_db/config_poi.json
tileview/Dockerfile

* The return value of `run_imposm_update` was not used, and the state file where the current db timestamp is persisted could be updated even if the update had failed.
* For easier maintenance, use the configuration defined in `ctx` instead of a custom `settings` object.

Fix osm update error handling

---

.travis.yml
exec.py
import_data/tasks/download.py
import_data/tasks/format_stdout.py
import_data/tasks/lock.py
import_data/tasks/osm_update.py
import_data/tasks/tasks.py
pyproject.toml

Attempt to cleanup a bit existing python scripts, though my humble point of perception. 
- Applied black formater and integration in the CI, like in Idunn
- Tried to fix large string defined in `tasks.py` breaking the identation
- Propagate the exceptions raised from concurrent tasks
- Simplify `exec.py` (it lost ~100 lines of code, and may be more maintainable and understandable from my point of view?)

Style cleanup

---

exec.py
import_data/import-wikidata/wikidata_functions.sql
kubernetes/templates/load_db.job.yaml

Fix a slightly annoying behavior introduced in https://github.com/QwantResearch/kartotherian_docker/pull/117.
When running  `./exec.py clean`, the script would first call `docker-compose up` (which waits until all docker images are running), then call `./exec.py down -v` (which will have to wait for all images to be stopped again).
(I also removed a few unbreakable spaces in other files)

exec.py: do not start images before cleaning

---

docker-compose.yml
import_data/invoke.yaml
import_data/sql-overrides/osml10n_overrides.sql
import_data/tasks/tasks.py
load_db/Dockerfile

Upgrade to latest openmaptiles/postgis image, to work around with slow `CLUSTER` commands during imposm optimization process.
A few cascading changes following this update:
* `-optimize` is now optional in imposm commands, to make future debugging easier. Still enabled by default
* The new openmaptiles/postgis images comes with an upgrade to mapnik-german-osml10n v2.5.9 that includes an performance regression (see https://github.com/giggls/mapnik-german-l10n/issues/54) 
The function `osml10n_get_country` needs to be overridden.
* imposm3 v0.10 -> v0.11 because of an incompatibility with PostGIS 3.0 (see https://github.com/omniscale/imposm3/pull/248)

Update to latest openmaptiles/postgis image, including postgis 3.0

---

import_data/import-wikidata/wikidata_functions.sql
import_data/invoke.yaml
import_data/tasks/tasks.py

Apply a cube function to the weight computed for the POIs.
The goal is to increase visibility of very known POIs. This change seems to fix some very obvious example such as "Le Louvre", but has no effect on others (eg. Opera in Paris where the train station is famous enough to often being put first).
This PR cannot affect tiles as the order in weights is preserved.

import_data: increase gap between lower and higher weights

---

tilerator/config.api.yaml
tilerator/config.worker.yaml

This debug stream depends on an optional dependency (`'bunyan-prettystream'`), that is no longer installed. 
And it's not suitable for production anyway (https://github.com/hadfieldn/node-bunyan-prettystream#readme).

tilerator: disable 'debug' stream in logging configuration

---

docker-compose.yml

The image is built from https://github.com/openmaptiles/openmaptiles-tools/tree/4dfdc1ab1ccdb0475cd94ebd8570fc255e3f8024
It also contains a fix about file system permissions in the "postgres" base image: https://github.com/docker-library/postgres/pull/804

Update postgis image, with recent 'postgres' base image

---

docker-compose.yml
import_data/tasks/tasks.py

For conformity with k8s best practices, the container should be read-only.

load_db: do not use current directory as download destination

---

kartotherian/Dockerfile
kartotherian/config.yaml

Some values used to be hardcoded in "kartotherian/config.yaml"
New environment variables for Kartotherian to make the configuration easier:
* `KARTOTHERIAN_PORT`:  default 6533
* `KARTOTHERIAN_TELEGRAF_HOST`: host used to connect to Telegraf (where statsd metrics will be sent).
These metrics will be disabled if this variable is empty.
* `KARTOTHERIAN_TELEGRAF_PORT`: default 8125

kartotherian: Define more environment variables for configuration

---

.github/workflows/ci.yml
docker-compose.yml
import_data/tasks/tasks.py
kartotherian/Dockerfile
load_db/import_data.sh
tilerator/Dockerfile

allow using entrypoint without config file (use invoke.yaml as fallback allow to override via env var)
push images also for branches with open PR
upgrade debian version to buster
uniformize the python version >3.6 as needed by nodejs build process

Qmaps-2322 upgrade debian  (to buster) and python  (to 3.6) version
